#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: jupyterimagepullers.submarine.apache.org
  labels:
    app.kubernetes.io/name: submarine-operator
    app.kubernetes.io/version: "0.7.0"
    app.kubernetes.io/component: jupyter-image-puller-operator
    app.kubernetes.io/managed-by: helm
spec:
  group: submarine.apache.org
  names:
    kind: JupyterImagePuller
    listKind: JupyterImagePullerList
    plural: jupyterimagepullers
    singular: jupyterimagepuller
    shortNames:
    - jip
    categories:
    - all
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              images:
                type: array
                description: the list of images to pre-pull
                items:
                  type: object
                  properties:
                    name:
                      description: environment name
                      type: string
                    image:
                      type: string
                      description: the name of image, must be NAME[:TAG|@DIGEST]
                    auth:
                      type: object
                      description: docker registry authentication
                      properties:
                        username:
                          type: string
                        password:
                          type: string
                        email:
                          type: string
                        secret:
                          type: string
                          description: if there is already a specified secret, we can fill in the secret name 
            nodeSelector:
              type: object
              description: node selector applied to pods created by the daemonset
            refreshHours:
              type: integer
              description: number of hours between health checks
          status:
            description: the observed state of JupyterImagePuller
            type: object
            properties:
              pullerImages:
                type: array
                description: the current state of puller images
                items:
                  type: object
                  properties:
                    name:
                      type: string
                      description: the name of image
                    state:
                      type: string
                      description: the current state of puller image, can be success, failure, pulling or others k8s image state
                    message:
                      type: string
                      description: the message of pulling the image, it can help handle the failure of image pulling
                    digest:
                      type: string
                      description: the digest of current image in nodes 
                    nodes:
                      type: array
                      description: which nodes have cached this image
                      items:
                        type: string
    served: true
    storage: true
    subresources:
      status: {}
